# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt         # Checks code formatting
    - goimports     # Checks import ordering
  settings:
    goimports:
      local-prefixes:
        - github.com/leefowlercu/agentic-memorizer

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - staticcheck   # Static analysis checks (includes gosimple)
    - ineffassign   # Detects unused variable assignments
    - unused        # Checks for unused code
    - misspell      # Finds misspelled English words
    - bodyclose     # Checks HTTP response body is closed
    - nilerr        # Finds code returning nil with non-nil error
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too noisy for most projects
    misspell:
      locale: US
  exclusions:
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - errcheck
          - bodyclose
      # Exclude testdata directories
      - path: testdata/
        linters:
          - errcheck
          - govet
