# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt         # Checks code formatting
    - goimports     # Checks import ordering
  settings:
    goimports:
      local-prefixes:
        - github.com/leefowlercu/agentic-memorizer

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - staticcheck   # Static analysis checks (includes gosimple)
    - ineffassign   # Detects unused variable assignments
    - unused        # Checks for unused code
    - misspell      # Finds misspelled English words
    - bodyclose     # Checks HTTP response body is closed
    - nilerr        # Finds code returning nil with non-nil error
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        # fmt print functions - errors only occur if writer fails
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
        - fmt.Printf
        - fmt.Println
        - fmt.Scanln
        # Common defer close patterns - errors rarely actionable
        - (io.Closer).Close
        - (*os.File).Close
        - (*bufio.Writer).Flush
        - (net.Conn).Close
        - (*net/http.Response).Body.Close
        # Database - defer close/rollback patterns
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        - (*database/sql.DB).Close
        # OS operations - often best-effort
        - os.Setenv
        - os.Remove
        # Writer flush - errors surfaced on prior writes
        - (*text/tabwriter.Writer).Flush
        # JSON encoder to response writers
        - (*encoding/json.Encoder).Encode
        # Application event bus - fire-and-forget publishing
        - (github.com/leefowlercu/agentic-memorizer/internal/events.Bus).Publish
        # Provider registry - errors logged internally
        - (*github.com/leefowlercu/agentic-memorizer/internal/providers.Registry).RegisterSemantic
        - (*github.com/leefowlercu/agentic-memorizer/internal/providers.Registry).RegisterEmbeddings
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too noisy for most projects
        - shadow          # Shadowing err is idiomatic Go
    misspell:
      locale: US
  exclusions:
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - errcheck
          - bodyclose
          - govet
      # Exclude testdata directories
      - path: testdata/
        linters:
          - errcheck
          - govet
